### ISSUE TITLE
Installing package Microsoft.ML on target framework .NET Framework 4.6.2 fails.

### ISSUE THREAD

**Issue by iSatishYadav** [dotnet/machinelearning#717]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: .NET 4.6.2

### Issue

- **What did you do?**
Tried to install Nuget Package `Microsoft.ML` on a `.NET 4.6.2` project in Visual Studio 2013 (Version 12.0.40629.00 Update 5)

- **What happened?**
Nuget Package installation failed with error.

- **What did you expect?**
Nuget Package should have been installed successfully as `netstandard 2.0` supports `.NET Framework 4.6.2`.

### Source code / logs
````
Installing 'Microsoft.ML 0.4.0'.
Successfully installed 'Microsoft.ML 0.4.0'.
Adding 'Microsoft.ML 0.4.0' to XXX.
Uninstalling 'Microsoft.ML 0.4.0'.
Successfully uninstalled 'Microsoft.ML 0.4.0'.
Install failed. Rolling back...
Could not install package 'Microsoft.ML 0.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
````

**Comment by GalOshri** [comment]
I am able to repro the issue with Visual Studio 2013. 

This seems similar to #290. @eerhardt, any ideas?

**Comment by JRAlexander** [comment]
This is still happening with 0.5.0

**Comment by eerhardt** [comment]
I don't believe Visual Studio 2013 supports `netstandard2.0`, but I have no hard information to back that up.

@nguerrera @dsplaisted @joperezr @AlexGhiondea - is it expected that I can use a `netstandard2.0` library in VS 2013?  My assumption was that I needed to either:

1. Use VS 2015 with 
    1. The latest NuGet VSIX for VS 2015 (v3.6.0 as of this writing) from https://www.nuget.org/downloads
    2. The .NET Standard Build Support extension from https://aka.ms/netstandard-build-support-netfx
2. Use VS 2017

**Comment by JRAlexander** [comment]
I'm using VS 2017. A .NET Framework 4.62 project in a solution will not allow me to reference a .NET standard 2.0 ML.NET project in the same solution.

**Comment by eerhardt** [comment]
> I'm using VS 2017

Then you aren't hitting the same problem described in this issue. Can you open a new issue with your repro steps and environment information?

**Comment by JRAlexander** [comment]
Yes, I can. Thanks.

**Comment by joperezr** [comment]
> I don't believe Visual Studio 2013 supports netstandard2.0, but I have no hard information to back that up.

That's right. The NuGet libraries that shipped with 2013 which contain the mappings between different frameworks most likely don't know about netstandard2.0 yet nor their compatibility with .NET 4.6.2. Upgrading to a newer version of VS should fix this issue.

@JRAlexander if you are using VS 2017 I would totally expect this problem not to happen, so if you open an issue please tag me so that we can investigate what is gonig on.

**Comment by eerhardt** [comment]
Closing as "Won't Fix", since VS 2013 doesn't support `netstandard2.0` libraries.

**Comment by kjsbedi** [comment]
@JRAlexander I am using using VS 2017 and when I am trying to install ML.NET 0.50 I am getting following error:

everity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Microsoft.ML 0.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Please help

**Comment by eerhardt** [comment]
@kjsbedi - Microsoft.ML is a `netstandard2.0` package, which is only compatible on .NET Framework v4.6.1 or later. You are using `v4.5.2`. You will need to re-target your project to .NET Framework v4.6.1 or later in order to use it. You can change the target framework version in the project property pages in VS.

**Comment by yusufmsalh** [comment]
I have tried installing MlL.net on VS 2015 .Net Framework v4.6.1 still facing the same issue 
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Microsoft.ML 0.11.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by eerhardt** [comment]
@yusufmsalh - did you do the following?

1. Use VS 2015 with 
    1. The latest NuGet VSIX for VS 2015 (v3.6.0 as of this writing) from https://www.nuget.org/downloads
    2. The .NET Standard Build Support extension from https://aka.ms/netstandard-build-support-netfx

**Comment by yusufmsalh** [comment]
I did the two steps above as you mentioned them ,now I'm facing another error and if You may help me:
Severity	Code	Description	Project	File	Line	Suppression State
Error		**Microsoft.ML currently supports 'x64' and 'x86' processor architectures. Please ensure your application is targeting 'x64' or 'x86'.**

**Comment by yusufmsalh** [comment]
I tried to resolve it using this [link](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-configure-projects-to-target-platforms?view=vs-2017) ,
now I have a lot of error saying duplicate references 
like this 
**Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1703	Multiple assemblies with equivalent identity have been imported: 'C:\Program Files (x86)\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\ref\System.Collections.Concurrent.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\System.Collections.Concurrent.dll'. Remove one of the duplicate references.	**

**Comment by yusufmsalh** [comment]
I have resolved by switching back to Dot Net Framework V4.6 , I wonder if you may find another solution for the duplicate reference issue  @eerhardt

**Comment by eerhardt** [comment]
> Microsoft.ML currently supports 'x64' and 'x86' processor architectures. Please ensure your application is targeting 'x64' or 'x86'.

As the error indicates, you can't use `Any CPU` with Microsoft.ML. Instead you need to change your project's platform to either `x64` or `x86`. See https://docs.microsoft.com/en-us/visualstudio/ide/how-to-configure-projects-to-target-platforms for instructions on how to change it.

**Comment by yusufmsalh** [comment]
Yes Eric ,I have solved this issue ,
Yet you may follow the thread,
i am still facing an issue for using ML.Net on Visual Studio 2015, Dot Net
Framework 4.6.1

**Comment by HardyRas** [comment]
> > Microsoft.ML currently supports 'x64' and 'x86' processor architectures. Please ensure your application is targeting 'x64' or 'x86'.
> 
> As the error indicates, you can't use `Any CPU` with Microsoft.ML. Instead you need to change your project's platform to either `x64` or `x86`. See https://docs.microsoft.com/en-us/visualstudio/ide/how-to-configure-projects-to-target-platforms for instructions on how to change it.

A save!
